version: "3.8"

services:
  backend:
    build: .
    container_name: springboot-backend
    ports:
      - "8080:8080"
    environment:
      # Use Railway's MySQL credentials
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql.railway.internal:3306/railway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: uwQpaEbOHnmnCavKUxOBCNpqzoQunrwW
